"""Protocolos (interfaces) da aplicação — DIP via typing.Protocol."""
from typing import Optional, Protocol

from app.models.protocolo import Protocolo


class ProtocoloRepositoryProtocol(Protocol):
    async def buscar_por_numero(self, numero: str) -> Optional[Protocolo]: ...
    async def buscar_por_id(self, id: int) -> Optional[Protocolo]: ...
    async def salvar(self, protocolo: Protocolo) -> Protocolo: ...
    async def deletar(self, protocolo: Protocolo, deletar_entries: bool = True) -> int: ...
